name: Update Public Gist Index

on:
  schedule:
    # Daily at 13:00 UTC (≈ 9:00 AM America/New_York)
    - cron: "0 13 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (not strictly needed but standard)
        uses: actions/checkout@v4

      # Pin Python 3.12 on the runner
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # pinned
      # ref: official setup-python action docs. :contentReference[oaicite:0]{index=0}

      # Install uv and enable its built-in cache
      - name: Set up uv (with cache)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      # refs: setup-uv marketplace/docs & CI guide. :contentReference[oaicite:1]{index=1}

      # Run the script via uv
      - name: Generate & update index gist
        env:
          GITHUB_USERNAME: "RichLewis007"                 # change if needed
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}         # token with gist read/write
          INDEX_GIST_ID: ${{ secrets.INDEX_GIST_ID }}     # your gist ID
        run: |
          uv --version
          # If you added pyproject.toml with requests, plain `uv run` is enough:
          # uv run python gist_index.py
          # Otherwise, pull requests on the fly:
          uv run --with requests python gist_index.py
